### ISSUE TITLE
Unable to Accept a Revision

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-client#924] opened 2018-06-20 18:07 UTC
<img width="1440" alt="civic" src="https://user-images.githubusercontent.com/13948978/41676232-7783625a-748a-11e8-9803-96a573a0e295.png">

I am unable, as editor, to accept EID 2861 revision as pictured above. One thing to note is that there was an action performed from the admin interface previously that may have created this subsequent conflict now.

**Comment by susannasiebert** [comment] 2018-06-21 15:16
The problem is that the actual change for the drug field is from id `[13]` to ids `[13,444]` where a drug with ID `444` does not exist in the database (anymore?). There are a few solution here, I think. You could reject the suggestion and then recreate it with a corrected second drug entry. I can probably also update the database entry to the correct value but that seems hacky.

**Comment by susannasiebert** [comment] 2018-06-22 16:16
After talking to KK it was decided that the affected revisions would be rejected and recreated with the correct drug entities. Closing this issue

**Closed by susannasiebert** 2018-06-22 16:16 UTC
Labels: bug
