### ISSUE TITLE
hide rejected evidence items by default

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/civic-client#791] opened 2017-07-06 16:15 UTC
All of these rejected EIDs should get removed to prevent cluttering up the evidence for a variant.

![image](https://user-images.githubusercontent.com/811065/27921098-4a7e08fc-623c-11e7-8605-7f1d5387b8f1.png)

**Comment by malachig** [comment] 2017-07-06 16:29
I think this particular examples should be deleted.  But in general the intent is to not show rejected items.  I believe the problem is a bug a in the grid menu that controls what is shown/hidden here.  I can't get the "show rejected" toggle to work right now...

**Comment by ahwagner** [comment] 2017-07-06 16:34
It looks like the "hide rejected" button doesn't work if a rejected EID is currently selected.

I propose that we make "hide rejected" the default behavior, though.

**Comment by jmcmichael** [comment] 2017-07-06 16:39
Yeah, hiding rejected EID rows won't work if a rejected EID is currently selected, as I thought it would be odd to not show the selected row in the grid. I recall giving up on showing a rejected EID at the same time as filtering out all other rejected EID rows. I could revisit this to see if it's easier to do now with the upgraded ui-grid component.

**Comment by jmcmichael** [comment] 2018-03-15 18:48
The logic for showing/hiding various rows depending on a variety of conditions is rather convoluted in the evidence grid. Currently rejected evidence items are only shown by default if the currently selected evidence item (reached by a direct link) is itself rejected, by default they are hidden. I'll keep this enhancement in mind when implementing the v2 datagrid, closing for v1.

**Closed by jmcmichael** 2018-03-15 18:48 UTC
