### ISSUE TITLE
add variant field to edit evidence form

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#783] opened 2017-06-22 18:57 UTC
Users should be able to associate evidence with a different variant w/o having to use the admin backend. Should behave the same as the Variant field on the Add Evidence form. Server expects the same info as with the Add Evidence form.

**Comment by juheon** [comment] 2017-06-22 21:06
I have three questions before I work on this issue. I am attaching input fields for EDIT EVIDENCE and ADD EVIDENCE forms. I highlighted with red if the fields are mentioned at least once in my list of questions. '*' indicates a required field. 

<img width="231" alt="screen shot 2017-06-22 at 4 02 45 pm" src="https://user-images.githubusercontent.com/4859572/27455914-972155e8-5764-11e7-9b86-74be3a0ceb08.png">

1) EDIT EVIDENCE and ADD EVIDENCE have different fields. For instance, "EDIT" form does not have "Gene Entrez Name", "Variant Name". "ADD" form does not have "Drug Names". In addition to "Variant Name", do you want me to add "Gene Entrez Name" on "EDIT" form and "Drug Names" on "ADD" form?
2) Required fields are different in two forms. "Rating" is not required in "EDIT" form and "Variant Origin" and "Evidence Direction" is not in "ADD" form. Should I make them required in both forms?
3) The order of fields (Variant Origin, Pubmed ID) is different. In "EDIT" form, "Variant Origin" is ahead "Pubmed ID" but in "ADD" form, it is in reverse order. Should I make them in the same order?

**Comment by jmcmichael** [comment] 2017-06-23 15:59
A1: The Add Evidence form confusingly contains fields associated with Genes, Variants, and Evidence. So a submission from the form could actually create a new gene and variant in addition to an evidence item. Hence, the Add Evidence fields can be found on the edit Gene, Variant, and Evidence Edit forms. For instance Gene Name appears on the Edit Gene form (however at the moment it's not edible).

Drug Names is present on the Add Evidence form, but the field only appears if evidence type 'Predictive' is selected - drugs aren't relevant to the other evidence types.

A2:  Some of the fields aren't required on the Edit form, as our automated import processes often result in records that have several un-filled fields. Curators may wish to only update a single field, and leave the others un-filled when making a submission. If all those fields were required, they would have to fill all the fields before submitting a change. That's why Rating and Evidence Direction aren't a required fields in the Edit form.

A3: Yeah, it would be good to have the field orders match up on both forms.

**Comment by jmcmichael** [comment] 2017-06-23 16:23
There's an issue with this new feature that I just thought of. When an editor accepts a suggested change, this function is called: 

https://github.com/griffithlab/civic-client/blob/master/src/components/services/EvidenceService.js#L209-L227

It sends the accept request to the server, and after the response returns, flushes the cache of all relevant entity data, and requests updated data from the server in order to update the UI.

This will work fine for all accepted changes except a parent variant update, as after the change is applied, the parent variant ID is no longer valid - the evidence item will need to be shown by the UI as parented to a new variant entirely.

Adam and I have discussed a quick fix for this that we can go over in more detail - basically, to redirect the user to the new revision using the server's short-link URLs if a suggested change includes a switch to a new variant.

**Comment by juheon** [comment] 2017-06-26 17:50
I think your new feature is good for the CIViC since people make mistakes. 

I will add the "Variant Name" field in the edit form and make fields in the same order - "Variant Name", "Variant origin", "Pubmed ID".

**Comment by juheon** [comment] 2017-07-18 23:18
I have a question about how to use 'filter' in the query. What kind of document should I read to understand the mechanisms of filter argument?

In the EDIT EVIDENCE form, I need the VARIANT NAME, but I only have the VARIANT ID. From the ADD EVIDENCE form, I found the script using Datatables.query filtered by VARIANT NAME.
https://github.com/griffithlab/civic-client/blob/2c01be8ef05a4f231539820e97ef2c57cded6fa4/src/app/views/add/evidence/addEvidenceBasic.js#L190-L201
I think I can modify this script to be filtered by VARIANT ID. 
I googled to find the relevant document but I could not find. Could you suggest search keywords? I tried 
* REST api query filter
* ngresource query filter

**Comment by juheon** [comment] 2017-07-31 19:20
I added "Variant Name" input to the EDIT EVIDENCE form. When I changed the Variant Name and hit the submit button, it called "EvidenceRevisions.submitRevision" with the edited Variant Name. However, it returned "Bad request" because "The suggested change was identical to the existing item".
I think the back end script should be modified to use the "Variant Name". 

I pulled my edited script to my repository (https://github.com/juheon/civic-client/blob/master/src/app/views/events/evidence/edit/evidenceEditBasic.js) but I did not pull the request since the script should be tested after the back end script is edited.

**Comment by susannasiebert** [comment] 2018-11-05 21:30
This is a duplicate of #748

**Comment by arpaddanos** [comment] 2020-02-13 20:04
Unclear why this issue was closed, as this functionality is not yet implemented.

**Comment by susannasiebert** [comment] 2020-02-13 20:08
Because it's a duplicate of a different issue #748. We don't need both issues open

**Closed** 2020-02-13 20:31 UTC
Labels: enhancement
