### ISSUE TITLE
Mark All as Read should only apply to selected notification category

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-client#909] opened 2018-05-22 23:51 UTC
Currently the "Mark all as Read" blows away ALL notifications of any type. This is misleading (in the way it is presented) and not the desired behavior. For example, when you select "Subscribed Events" notifications, in the top bar it says "showing X of Y subscribed event notifications..." and then in that same bar we present the "Mark all as Read" button. The intuition (and desired behavior) here is that this will just mark the Y subscribed events as read. But instead it also marks other types of notifications, including Mentions as read. I don't know a way to reverse this. So, the result is that in an effort unclutter my notification of hundreds/thousands of subscribed events I lost a handful of important mentions. :-(

<img width="1149" alt="screen shot 2018-05-22 at 7 46 03 pm" src="https://user-images.githubusercontent.com/1638042/40396165-884d4f8a-5df9-11e8-8a92-b6098f190c0b.png">

**Comment by kkrysiak** [comment] 2018-11-01 19:53
This is duplicate of #513

**Closed by kkrysiak** 2018-11-01 19:53 UTC
Labels: bug
